# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: numbersApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10numbersApi.proto\x12\x07numbers\"$\n\x0cInputNumbers\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x18\n\x0bInputNumber\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\x18\n\x06Number\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xc2\x01\n\nNumbersApi\x12\x36\n\nSumNumbers\x12\x15.numbers.InputNumbers\x1a\x0f.numbers.Number\"\x00\x12\x39\n\x0bListNumbers\x12\x15.numbers.InputNumbers\x1a\x0f.numbers.Number\"\x00\x30\x01\x12\x41\n\x12\x43\x61lculateUntilZero\x12\x14.numbers.InputNumber\x1a\x0f.numbers.Number\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numbersApi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTNUMBERS']._serialized_start=29
  _globals['_INPUTNUMBERS']._serialized_end=65
  _globals['_INPUTNUMBER']._serialized_start=67
  _globals['_INPUTNUMBER']._serialized_end=91
  _globals['_NUMBER']._serialized_start=93
  _globals['_NUMBER']._serialized_end=117
  _globals['_NUMBERSAPI']._serialized_start=120
  _globals['_NUMBERSAPI']._serialized_end=314
# @@protoc_insertion_point(module_scope)
